export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Dahi-Chart',
    cookTime: '10-20',
    price: 60,
    favorite: false,
    origins: ['Indian'],
    stars: 4.5,
    imageUrl: 'assets/food1.jpg',
    tags: ['FastFood','Chart'],
  },
  {
    id:'2',
    name: 'Pizza',
    cookTime: '20-30',
    price: 120,
    favorite: true,
    origins: ['Italy','🍕'],
    stars: 4.5,
    imageUrl: 'assets/food2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'3',
    name: 'Burger',
    cookTime: '8-9',
    price: 100,
    favorite: true,
    origins: ['U.S','Germany','🍔'],
    stars: 4.5,
    imageUrl: 'assets/food3.jpg',
    tags: ['FastFood','Burger', 'Lunch'],
  },

  {
    id:'4',
    name: 'Mini-Burger',
    cookTime: '20-30',
    price: 70,
    favorite: false,
    origins: ['America','🍔'],
    stars: 4.5,
    imageUrl: 'assets/food4.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'5',
    name: 'French-Fries',
    cookTime: '5-6',
    price: 200,
    favorite:true,
    origins: ['Belgium','🍟'],
    stars: 4.5,
    imageUrl: 'assets/food5.jpg',
    tags: ['FastFood', 'Fries', 'Lunch'],
  },
  {
    id:'6',
    name: 'Tacos',
    cookTime: '30-40',
    price: 250,
    favorite:false,
    origins: ['Mexico','🌮'],
    stars: 4.5,
    imageUrl: 'assets/food6.jpg',
    tags: ['FastFood', 'Tacos', 'Lunch'],
  },
  {
    id:'7',
    name: 'Salad',
    cookTime: '4-5',
    price: 195,
    favorite:false,
    origins: ['Romans','Greeks','Indians','🥗'],
    stars: 4.5,
    imageUrl: 'assets/food7.jpg',
    tags: [ 'Salad', 'Lunch'],
  },
  {
    id:'8',
    name: 'Coffee',
    cookTime: '4-5',
    price: 100,
    favorite:true,
    origins: ['Romans','Greeks','Indian','☕'],
    stars: 4.5,
    imageUrl: 'assets/food8.jpg',
    tags: ['Coffee', 'Lunch'],
  },
  {
    id:'9',
    name: 'Chocolate Pastry',
    cookTime: '10-15',
    price: 40,
    favorite:true,
    origins: ['Egyptians','Greeks','Rome','🍰'],
    stars: 4.5,
    imageUrl: 'assets/food9.jpg',
    tags: ['Desert', 'Lunch'],
  }
]

export const sample_tags:any[] = [
  { name: 'All', count:9 },
  { name: 'FastFood', count:6 },
  { name: 'Pizza', count:1 },
  { name: 'Burger', count:2 },
  { name: 'Fries', count:1 },
  { name: 'Desert', count:1 },
]

export const sample_users: any[] = [
  {
    name: "Jon Doe",
    email: "jon@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "23456",
    address: "Toronto On",
    isAdmin: false,
  },
];